import React,{useEffect,useState} from 'react';
import {startPreviewSession} from '../game/authSession.js';

const TITLES={login:['BIENVENIDO DE NUEVO','Continúa tu aventura'],register:['NUEVO EXPLORADOR','Crea tu perfil'],recover:['RECUPERAR ACCESO','Volver al camino']};

export default function AuthScreen({onAuthenticated}){
  const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:'',confirm:'',remember:true}),[error,setError]=useState(''),[recoverySent,setRecoverySent]=useState(false);
  const [kicker,title]=TITLES[mode];
  useEffect(()=>{document.title='Valle Esmeralda · Acceso';},[]);
  const update=event=>setForm(current=>({...current,[event.target.name]:event.target.type==='checkbox'?event.target.checked:event.target.value}));
  const changeMode=next=>{setMode(next);setError('');setRecoverySent(false);};
  const submit=event=>{
    event.preventDefault();setError('');
    if(!/^\S+@\S+\.\S+$/.test(form.email)){setError('Escribe un correo válido.');return;}
    if(mode==='recover'){setRecoverySent(true);return;}
    if(form.password.length<6){setError('La contraseña debe tener al menos 6 caracteres.');return;}
    if(mode==='register'&&!form.name.trim()){setError('Escribe el nombre del explorador.');return;}
    if(mode==='register'&&form.password!==form.confirm){setError('Las contraseñas no coinciden.');return;}
    onAuthenticated(startPreviewSession({name:form.name,email:form.email},form.remember));
  };
  return <main className="auth-page"><section className="auth-visual" aria-label="El mundo fantástico de Valle Esmeralda"><img className="auth-landscape" src="./art/world-map-clean.webp" alt="Islas, cascadas y caminos de Valle Esmeralda"/><div className="auth-visual-shade"/><a className="auth-brand" href="?">VALLE <strong>ESMERALDA</strong><small>UNA AVENTURA POR DESCUBRIR</small></a><div className="auth-story"><img src="./art/hero-dodge-game.webp" alt="Protagonista de Valle Esmeralda"/><div><small>TU CAMINO COMIENZA AQUÍ</small><h1>Explora. Razona.<br/>Supera el desafío.</h1><p>Cada mundo pondrá a prueba una forma diferente de pensar.</p></div></div></section><section className="auth-panel"><div className="auth-card"><div className="auth-mobile-brand">VALLE <b>ESMERALDA</b></div><small>{kicker}</small><h2>{title}</h2><p className="auth-intro">{mode==='login'?'Ingresa para conservar tu lugar en el mapa.':mode==='register'?'Prepara la identidad que usarás durante la aventura.':'Indica el correo asociado a tu perfil.'}</p>{recoverySent?<div className="auth-recovery-result" role="status"><b>✦</b><h3>Solicitud preparada</h3><p>Cuando conectemos el sistema de usuarios, aquí se enviará el enlace para recuperar la contraseña.</p><button onClick={()=>changeMode('login')}>VOLVER A INICIAR SESIÓN</button></div>:<form onSubmit={submit}>{mode==='register'&&<label>Nombre del explorador<input name="name" value={form.name} onChange={update} autoComplete="name" placeholder="¿Cómo quieres aparecer?"/></label>}<label>Correo electrónico<input name="email" value={form.email} onChange={update} type="email" inputMode="email" autoComplete="email" placeholder="nombre@correo.com"/></label>{mode!=='recover'&&<label>Contraseña<input name="password" value={form.password} onChange={update} type="password" autoComplete={mode==='login'?'current-password':'new-password'} placeholder="Mínimo 6 caracteres"/></label>}{mode==='register'&&<label>Confirmar contraseña<input name="confirm" value={form.confirm} onChange={update} type="password" autoComplete="new-password" placeholder="Repite la contraseña"/></label>}{mode!=='recover'&&<label className="auth-remember"><input name="remember" checked={form.remember} onChange={update} type="checkbox"/> Recordarme en este dispositivo</label>}{error&&<strong className="auth-error" role="alert">{error}</strong>}<button className="auth-submit">{mode==='login'?'ENTRAR A LA AVENTURA →':mode==='register'?'CREAR PERFIL →':'RECUPERAR ACCESO →'}</button></form>}<div className="auth-switches">{mode!=='login'&&<button onClick={()=>changeMode('login')}>Ya tengo un perfil</button>}{mode!=='register'&&<button onClick={()=>changeMode('register')}>Crear usuario</button>}{mode!=='recover'&&<button onClick={()=>changeMode('recover')}>Olvidé mi contraseña</button>}</div><p className="auth-preview-note"><b>VERSIÓN DE PREPARACIÓN</b> Esta pantalla aún no crea cuentas en internet y nunca guarda la contraseña escrita.</p></div></section></main>;
}
