import React,{useEffect,useRef,useState} from 'react';
import {CANNON_COORDINATES,FUNCTION_CANNON_CHALLENGES,FUNCTION_GRAPH_CHALLENGES,LINEAR_LEVEL_CHALLENGES,cannonFlight} from '../game/cannonCoordinates.js';
import HubLinks from './HubLinks.jsx';
import {recordGameError} from '../game/progressTracking.js';

const PROGRESS_KEY='valle-esmeralda-logic-progress',gridX=x=>680+x*57,gridY=y=>445-y*52,SHOT_START={x:250,y:565};
const loadProgress=()=>{try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');}catch{return {};}};

export default function CannonCoordinateLevel({level,levels,onSelectLevel,onNext}){
 const [round,setRound]=useState(0),[marker,setMarker]=useState({x:0,y:0}),[projectile,setProjectile]=useState(null),[hearts,setHearts]=useState(2),[status,setStatus]=useState('aim'),[feedback,setFeedback]=useState(''),[mistakes,setMistakes]=useState(0),[shots,setShots]=useState(0),[menu,setMenu]=useState(false),[saved,setSaved]=useState(loadProgress),[solvedPoints,setSolvedPoints]=useState([]);
 const buildsGraph=level.functionGraph||level.linearFunction,isFunction=level.functionCannon||level.linearFunction;
 const challenges=level.linearFunction?LINEAR_LEVEL_CHALLENGES[level.linearSet??0]:level.functionGraph?FUNCTION_GRAPH_CHALLENGES:level.functionCannon?FUNCTION_CANNON_CHALLENGES:CANNON_COORDINATES,animation=useRef(0),delay=useRef(0),challenge=challenges[round];
 const prepare=()=>{setMarker({x:0,y:0});setProjectile(null);setStatus('aim');setFeedback('');};
 const restart=()=>{clearTimeout(delay.current);cancelAnimationFrame(animation.current);setRound(0);setHearts(2);setMistakes(0);setShots(0);setSolvedPoints([]);prepare();};
 useEffect(()=>()=>{clearTimeout(delay.current);cancelAnimationFrame(animation.current);},[]);
 useEffect(()=>{restart();},[level.id]);
 function movePoint(dx,dy){if(status!=='aim'||menu)return;setMarker(current=>({x:Math.max(-4,Math.min(4,current.x+dx)),y:Math.max(-3,Math.min(3,current.y+dy))}));}
 function launch(){if(status!=='aim'||menu)return;setStatus('flying');setShots(value=>value+1);const end={x:gridX(marker.x),y:gridY(marker.y)},started=performance.now();const tick=now=>{const progress=Math.min(1,(now-started)/1050);setProjectile(cannonFlight(SHOT_START,end,progress));if(progress<1){animation.current=requestAnimationFrame(tick);return;}const correct=marker.x===challenge.target.x&&marker.y===challenge.target.y;if(correct){if(buildsGraph)setSolvedPoints(current=>[...current,challenge.target]);setStatus('correct');setFeedback(isFunction?`¡Correcto! f(${challenge.input}) = ${challenge.target.y}. Impacto en (${marker.x}, ${marker.y}).`:`¡Impacto exacto en (${marker.x}, ${marker.y})!`);delay.current=setTimeout(()=>{if(round===challenges.length-1)setStatus('won');else{setRound(value=>value+1);prepare();}},1650);}else{recordGameError(level.id);const remaining=hearts-1;setHearts(remaining);setMistakes(value=>value+1);setStatus(remaining?'wrong':'lost');setFeedback(`El disparo llegó a (${marker.x}, ${marker.y}). ${challenge.hint}`);if(remaining)delay.current=setTimeout(prepare,2500);}};animation.current=requestAnimationFrame(tick);}
 useEffect(()=>{const key=e=>{if(e.key==='Escape'){setMenu(value=>!value);return;}if(menu)return;const commands={ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0],ArrowUp:[0,1],w:[0,1],ArrowDown:[0,-1],s:[0,-1]};const command=commands[e.key]||commands[e.key.toLowerCase()];if(command){e.preventDefault();movePoint(...command);}if(e.key==='Enter'||e.key===' '){e.preventDefault();launch();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 const stars=status==='won'?1+(mistakes===0?1:0)+(shots===4?1:0):0;
 useEffect(()=>{if(status!=='won')return;setSaved(current=>{const next={...current,[level.id]:{stars:Math.max(current[level.id]?.stars||0,stars),crystal:1}};localStorage.setItem(PROGRESS_KEY,JSON.stringify(next));return next;});},[status,level.id]);
 const chapterLevels=levels.filter(item=>item.logic||item.coordinate||item.cannonCoordinate),totalStars=chapterLevels.reduce((sum,item)=>sum+(saved[item.id]?.stars||0),0),totalCrystals=chapterLevels.reduce((sum,item)=>sum+(saved[item.id]?.crystal||0),0),maxStars=chapterLevels.length*3,maxCrystals=chapterLevels.length;
 return <main><header><a className="brand" href="?view=map"><span>VALLE</span> ESMERALDA<small>UNA AVENTURA POR DESCUBRIR</small></a><div className="chapter"><span>CAPÍTULO 03</span><strong>{level.name}</strong></div><div className="inventory"><span>★ <b>{totalStars}</b><small>/ {maxStars}</small></span><span>◆ <b>{totalCrystals}</b><small>/ {maxCrystals}</small></span><span className="energy">{Array.from({length:2},(_,i)=>i<hearts?'♥':'♡').join(' ')}</span></div><HubLinks/><button className="menu-button" onClick={()=>setMenu(true)}>☰</button></header>
 <section className={`game cannon-coordinate-game ${isFunction?'function-cannon-game':''}`}><svg className="world" viewBox="0 0 1200 800" role="img" aria-label="Cañón apuntando a una cuadrícula de coordenadas"><image href="./art/coordinate-observatory.webp" width="1200" height="800" preserveAspectRatio="xMidYMid slice"/><g className="coordinate-mission"><rect x="300" y="25" width="600" height="105" rx="17"/><text x="600" y="59" className="coordinate-kicker">{buildsGraph?'PUNTOS DE LA RECTA':level.functionCannon?'FUNCIÓN':'DISPARO'} {round+1}/4 · ELEGIDO ({marker.x}, {marker.y})</text><text x="600" y="101" className="coordinate-prompt">{isFunction?`${challenge.formula}     con x = ${challenge.input}`:challenge.prompt}</text></g>
 <g className="coordinate-grid cannon-grid">{Array.from({length:9},(_,i)=>i-4).map(x=><g key={`x${x}`}><line x1={gridX(x)} y1={gridY(3)} x2={gridX(x)} y2={gridY(-3)} className={x===0?'axis':'grid-line'}/><text x={gridX(x)} y={gridY(0)+22}>{x}</text></g>)}{Array.from({length:7},(_,i)=>i-3).map(y=><g key={`y${y}`}><line x1={gridX(-4)} y1={gridY(y)} x2={gridX(4)} y2={gridY(y)} className={y===0?'axis':'grid-line'}/>{y!==0&&<text x={gridX(0)-19} y={gridY(y)+5}>{y}</text>}</g>)}{isFunction&&<g className="function-input-line"><line x1={gridX(challenge.input)} y1={gridY(3)} x2={gridX(challenge.input)} y2={gridY(-3)}/><rect x={gridX(challenge.input)-40} y={gridY(-3)+12} width="80" height="30" rx="10"/><text x={gridX(challenge.input)} y={gridY(-3)+33}>x = {challenge.input}</text></g>}</g>{buildsGraph&&<g className="crystal-graph">{solvedPoints.length>1&&<polyline points={[...solvedPoints].sort((a,b)=>a.x-b.x).map(point=>`${gridX(point.x)},${gridY(point.y)}`).join(' ')}/>} {solvedPoints.map(point=><g key={`${point.x}-${point.y}`} transform={`translate(${gridX(point.x)} ${gridY(point.y)})`}><circle r="13"/><text y="-20">({point.x},{point.y})</text></g>)}</g>}
 <g className="coordinate-marker" transform={`translate(${gridX(marker.x)} ${gridY(marker.y)})`}><circle r="19"/><path d="M-29 0h58M0-29v58"/></g><image href="./art/cannon-transparent.webp" x="95" y="535" width="165" height="118"/>{status==='flying'&&<g className="coordinate-muzzle" transform={`translate(${SHOT_START.x} ${SHOT_START.y})`}><circle r="21"/><path d="M0-31 7-14 24-24 17-6 35 0 17 7 25 24 7 15 0 33-7 15-23 24-16 7-34 0-16-7-24-24-7-15Z"/></g>}<image href={status==='wrong'?'./art/hero-hurt.webp':'./art/hero-dodge.webp'} x="15" y="535" width="105" height="116"/>
 {projectile&&<g className="coordinate-projectile"><circle cx={projectile.x} cy={projectile.y} r="16"/><circle cx={projectile.x} cy={projectile.y} r="7"/></g>}{status==='correct'&&<g className="coordinate-burst" transform={`translate(${gridX(challenge.target.x)} ${gridY(challenge.target.y)})`}><circle r="35"/><text y="10">◆</text></g>}{status==='wrong'&&<g className="coordinate-miss" transform={`translate(${gridX(marker.x)} ${gridY(marker.y)})`}><path d="M-18-18 18 18M18-18-18 18"/></g>}{feedback&&<g className={`coordinate-feedback ${status}`}><rect x="315" y="680" width="570" height="58" rx="14"/><text x="600" y="716">{feedback}</text></g>}</svg>
 <div className="coordinate-controls"><div><strong>{buildsGraph?'CONSTRUYE LA RECTA DISPARO A DISPARO':level.functionCannon?'CALCULA f(x), COLOCA EL PUNTO Y DISPARA':'COLOCA EL PUNTO Y DISPARA'}</strong><small>{buildsGraph?'Calcula la salida, dispara y observa cómo cada acierto revela la pendiente de la recta.':level.functionCannon?'La línea dorada indica la entrada x. Calcula la salida y = f(x) y marca el punto (x, y).':'No se muestra la trayectoria antes del lanzamiento. El proyectil caerá exactamente donde marques.'}</small></div><div className="coordinate-pad"><button onClick={()=>movePoint(0,1)} disabled={status!=='aim'}>▲</button><button onClick={()=>movePoint(-1,0)} disabled={status!=='aim'}>◀</button><button className="mark-point cannon-fire" onClick={launch} disabled={status!=='aim'}>✦ LANZAR</button><button onClick={()=>movePoint(1,0)} disabled={status!=='aim'}>▶</button><button onClick={()=>movePoint(0,-1)} disabled={status!=='aim'}>▼</button></div></div>
 {status==='won'&&<div className="victory"><div className="win-star">{'★'.repeat(stars)}</div><small>NIVEL COMPLETADO</small><h1>{buildsGraph?'¡La recta está completa!':level.functionCannon?'¡Funciones al blanco!':'¡Coordenadas al blanco!'}</h1><p>{buildsGraph?`Tus cuatro impactos revelaron ${challenge.formula}.`:level.functionCannon?'Convertiste cuatro entradas x en sus salidas f(x) y acertaste cada coordenada.':'Los cuatro proyectiles llegaron exactamente a los puntos que marcaste.'}</p><div className="rewards">★ {stars} estrellas <span>◆ 1 cristal</span></div><button onClick={onNext}>Continuar →</button></div>}{status==='lost'&&<div className="victory defeat"><div className="win-star">♡</div><small>SIN ENERGÍA</small><h1>{isFunction?'Revisa la función':'Revisa el punto'}</h1><p>{challenge.hint}</p><button onClick={restart}>Reintentar ↻</button></div>}
 {menu&&<div className="modal-backdrop"><section className="menu-card logic-map"><small>MAPA DEL VALLE</small><h2>Capítulos desbloqueados</h2><button onClick={()=>setMenu(false)}>Continuar</button><div className="map-levels">{chapterLevels.map(item=>{const index=levels.findIndex(candidate=>candidate.id===item.id),record=saved[item.id];return <button className={item.id===level.id?'map-current':'secondary'} key={item.id} onClick={()=>onSelectLevel(index)}><b>Nivel {item.id}</b><span>{record?'★'.repeat(record.stars):'○ Sin completar'}</span></button>;})}</div></section></div>}</section><footer><div className="guide-icon">✧</div><p>{status==='wrong'?challenge.hint:isFunction?'Calcula la salida f(x), marca el punto (x, y) y dispara.':'Mueve el marcador hasta la coordenada indicada y pulsa LANZAR.'}</p><span className="attempts">Punto ({marker.x}, {marker.y}) · Disparo {round+1}/4</span></footer></main>;
}


