import React,{useEffect,useRef,useState} from 'react';
import {COORDINATE_CHALLENGES} from '../game/coordinateChallenges.js';
import HubLinks from './HubLinks.jsx';

const PROGRESS_KEY='valle-esmeralda-logic-progress',gridX=x=>600+x*70,gridY=y=>490-y*55;
const loadProgress=()=>{try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');}catch{return {};}};

export default function CoordinateLevel({level,levels,onSelectLevel,onNext}){
 const [round,setRound]=useState(0),[point,setPoint]=useState({x:0,y:0}),[display,setDisplay]=useState({x:0,y:0,jump:0}),[moving,setMoving]=useState(false),[hearts,setHearts]=useState(2),[status,setStatus]=useState('playing'),[feedback,setFeedback]=useState(''),[mistakes,setMistakes]=useState(0),[moves,setMoves]=useState(0),[menu,setMenu]=useState(false),[saved,setSaved]=useState(loadProgress);
 const animation=useRef(0),delay=useRef(0),challenge=COORDINATE_CHALLENGES[round];
 const prepare=()=>{setPoint({x:0,y:0});setDisplay({x:0,y:0,jump:0});setMoving(false);setStatus('playing');setFeedback('');};
 const restart=()=>{clearTimeout(delay.current);cancelAnimationFrame(animation.current);setRound(0);setHearts(2);setMistakes(0);setMoves(0);prepare();};
 useEffect(()=>()=>{clearTimeout(delay.current);cancelAnimationFrame(animation.current);},[]);
 const move=(dx,dy)=>{if(moving||status!=='playing'||menu)return;const target={x:Math.max(-4,Math.min(4,point.x+dx)),y:Math.max(-3,Math.min(3,point.y+dy))};if(target.x===point.x&&target.y===point.y)return;const from={...display},started=performance.now();setPoint(target);setMoving(true);setMoves(value=>value+1);const step=now=>{const p=Math.min(1,(now-started)/280),ease=1-Math.pow(1-p,3);setDisplay({x:from.x+(target.x-from.x)*ease,y:from.y+(target.y-from.y)*ease,jump:Math.sin(Math.PI*p)*18});if(p<1)animation.current=requestAnimationFrame(step);else setMoving(false);};animation.current=requestAnimationFrame(step);};
 const mark=()=>{if(moving||status!=='playing'||menu)return;const correct=point.x===challenge.target.x&&point.y===challenge.target.y;if(!correct){const remaining=hearts-1;setHearts(remaining);setMistakes(value=>value+1);setStatus(remaining?'wrong':'lost');setFeedback(`Marcaste (${point.x}, ${point.y}). ${challenge.hint}`);if(remaining)delay.current=setTimeout(prepare,1900);return;}setStatus('correct');setFeedback(`¡Correcto! El punto es (${challenge.target.x}, ${challenge.target.y}).`);delay.current=setTimeout(()=>{if(round===COORDINATE_CHALLENGES.length-1)setStatus('won');else{setRound(value=>value+1);prepare();}},1500);};
 useEffect(()=>{const key=e=>{if(e.key==='Escape'){setMenu(value=>!value);return;}if(menu)return;const commands={ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0],ArrowUp:[0,1],w:[0,1],ArrowDown:[0,-1],s:[0,-1]};const command=commands[e.key]||commands[e.key.toLowerCase()];if(command){e.preventDefault();move(...command);}if(e.key==='Enter'||e.key===' '){e.preventDefault();mark();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 const stars=status==='won'?1+(mistakes===0?1:0)+(moves<=18?1:0):0;
 useEffect(()=>{if(status!=='won')return;setSaved(current=>{const next={...current,18:{stars:Math.max(current[18]?.stars||0,stars),crystal:1}};localStorage.setItem(PROGRESS_KEY,JSON.stringify(next));return next;});},[status]);
 const chapterLevels=levels.filter(item=>item.logic||item.coordinate||item.cannonCoordinate),totalStars=chapterLevels.reduce((sum,item)=>sum+(saved[item.id]?.stars||0),0),totalCrystals=chapterLevels.reduce((sum,item)=>sum+(saved[item.id]?.crystal||0),0),maxStars=chapterLevels.length*3,maxCrystals=chapterLevels.length;
 return <main><header><a className="brand" href="?view=map"><span>VALLE</span> ESMERALDA<small>UNA AVENTURA POR DESCUBRIR</small></a><div className="chapter"><span>CAPÍTULO 03</span><strong>{level.name}</strong></div><div className="inventory"><span>★ <b>{totalStars}</b><small>/ {maxStars}</small></span><span>◆ <b>{totalCrystals}</b><small>/ {maxCrystals}</small></span><span className="energy">{Array.from({length:2},(_,i)=>i<hearts?'♥':'♡').join(' ')}</span></div><HubLinks/><button className="menu-button" onClick={()=>setMenu(true)}>☰</button></header>
 <section className="game coordinate-game"><svg className="world coordinate-world" viewBox="0 0 1200 800" role="img" aria-label="Observatorio con plano cartesiano"><image href="./art/coordinate-observatory.webp" width="1200" height="800" preserveAspectRatio="xMidYMid slice"/><g className="coordinate-mission"><rect x="300" y="25" width="600" height="105" rx="17"/><text x="600" y="59" className="coordinate-kicker">DESAFÍO {round+1}/4 · POSICIÓN ACTUAL ({point.x}, {point.y})</text><text x="600" y="101" className="coordinate-prompt">{challenge.prompt}</text></g>
 <g className="coordinate-grid">{Array.from({length:9},(_,i)=>i-4).map(x=><g key={`x${x}`}><line x1={gridX(x)} y1={gridY(3)} x2={gridX(x)} y2={gridY(-3)} className={x===0?'axis':'grid-line'}/><text x={gridX(x)} y={gridY(0)+24}>{x}</text></g>)}{Array.from({length:7},(_,i)=>i-3).map(y=><g key={`y${y}`}><line x1={gridX(-4)} y1={gridY(y)} x2={gridX(4)} y2={gridY(y)} className={y===0?'axis':'grid-line'}/>{y!==0&&<text x={gridX(0)-21} y={gridY(y)+6}>{y}</text>}</g>)}<path d={`M${gridX(4)-12} ${gridY(0)-8}l12 8-12 8M${gridX(0)-8} ${gridY(3)+12}l8-12 8 12`} className="axis-arrow"/><text x={gridX(4)+19} y={gridY(0)+6} className="axis-name">x</text><text x={gridX(0)+16} y={gridY(3)-8} className="axis-name">y</text></g>
 <circle className="origin-glow" cx={gridX(0)} cy={gridY(0)} r="13"/><ellipse className="coordinate-shadow" cx={gridX(display.x)} cy={gridY(display.y)+34} rx={26-display.jump*.18} ry="7"/><g className={status==='wrong'?'coordinate-hero hurt':'coordinate-hero'} transform={`translate(${gridX(display.x)-36} ${gridY(display.y)-53-display.jump})`}><image href={status==='wrong'?'./art/hero-hurt.webp':'./art/hero-dodge.webp'} width="72" height="80"/></g>
 {status==='correct'&&<g className="marked-point"><circle cx={gridX(challenge.target.x)} cy={gridY(challenge.target.y)} r="28"/><text x={gridX(challenge.target.x)} y={gridY(challenge.target.y)+8}>✓</text></g>}{feedback&&<g className={`coordinate-feedback ${status}`}><rect x="315" y="675" width="570" height="62" rx="14"/><text x="600" y="713">{feedback}</text></g>}</svg>
 <div className="coordinate-controls"><div><strong>MUÉVETE POR LA CUADRÍCULA</strong><small>Lee primero x y después y. Confirma solamente cuando estés seguro.</small></div><div className="coordinate-pad"><button onClick={()=>move(0,1)} disabled={moving||status!=='playing'}>▲</button><button onClick={()=>move(-1,0)} disabled={moving||status!=='playing'}>◀</button><button className="mark-point" onClick={mark} disabled={moving||status!=='playing'}>◆ MARCAR</button><button onClick={()=>move(1,0)} disabled={moving||status!=='playing'}>▶</button><button onClick={()=>move(0,-1)} disabled={moving||status!=='playing'}>▼</button></div></div>
 {status==='won'&&<div className="victory"><div className="win-star">{'★'.repeat(stars)}</div><small>NIVEL COMPLETADO</small><h1>¡Mapa descifrado!</h1><p>Ubicaste puntos directos y dedujiste coordenadas a partir de pistas.</p><div className="rewards">★ {stars} estrellas <span>◆ 1 cristal</span></div><button onClick={onNext}>Continuar →</button></div>}{status==='lost'&&<div className="victory defeat"><div className="win-star">♡</div><small>COORDENADA INCORRECTA</small><h1>Vuelve al origen</h1><p>{challenge.hint}</p><button onClick={restart}>Reintentar ↻</button></div>}
 {menu&&<div className="modal-backdrop"><section className="menu-card logic-map"><small>MAPA DEL VALLE</small><h2>Capítulos desbloqueados</h2><button onClick={()=>setMenu(false)}>Continuar</button><div className="map-levels">{chapterLevels.map(item=>{const index=levels.findIndex(candidate=>candidate.id===item.id),record=saved[item.id];return <button className={item.id===18?'map-current':'secondary'} key={item.id} onClick={()=>onSelectLevel(index)}><b>Nivel {item.id}</b><span>{record?'★'.repeat(record.stars):'○ Sin completar'}</span></button>;})}</div></section></div>}</section><footer><div className="guide-icon">✧</div><p>{status==='wrong'?challenge.hint:'Recuerda: primero se lee el eje horizontal x y después el vertical y.'}</p><span className="attempts">Punto ({point.x}, {point.y}) · Desafío {round+1}/4</span></footer></main>;
}
