import React,{useEffect,useRef,useState} from 'react';
import HubLinks from './HubLinks.jsx';

const KEY='valle-esmeralda-logic-progress';
const PATTERNS=[[1,3,2,0],[2,0,3,1],[3,2,0,1]],GLYPHS=['─','╲','│','╱'],LANES=[350,600,850];
const POINTS=[{x:280,y:475},{x:485,y:390},{x:715,y:390},{x:920,y:475}],DIRS=[[0,-1],[1,-1],[1,0],[1,1]];
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};

export default function DarkBossLevel({level,onNext}){
 const [round,setRound]=useState(0),[mirrors,setMirrors]=useState([0,0,0,0]),[lane,setLane]=useState(1),[hearts,setHearts]=useState(3),[warning,setWarning]=useState(null),[impact,setImpact]=useState(null),[status,setStatus]=useState('playing'),[flash,setFlash]=useState(false),[attacks,setAttacks]=useState(0),[saved,setSaved]=useState(read),laneRef=useRef(1),attackRef=useRef(0),lockRef=useRef(0);
 laneRef.current=lane;
 const target=PATTERNS[Math.min(round,2)],wrong=mirrors.findIndex((v,i)=>v!==target[i]),aligned=wrong<0,reached=aligned?4:wrong;
 const channel=[[160,610],...POINTS.map(p=>[p.x,p.y]),[600,190]],beam=[[160,610],...POINTS.slice(0,reached+1).map(p=>[p.x,p.y])];
 if(aligned)beam.push([600,190]);else{const p=POINTS[reached],d=DIRS[mirrors[reached]];beam.push([p.x+d[0]*115,p.y+d[1]*115])}
 const asPoints=a=>a.map(p=>p.join(',')).join(' ');
 useEffect(()=>{if(status!=='playing')return;let next,strike,clear,active=true;const prepare=()=>{if(!active)return;const chosen=(attackRef.current+++round*2+1)%3;setAttacks(v=>v+1);setWarning(chosen);strike=setTimeout(()=>{if(!active)return;setWarning(null);setImpact(chosen);clear=setTimeout(()=>setImpact(null),450);const now=Date.now();if(laneRef.current===chosen&&now>=lockRef.current){lockRef.current=now+1800;setHearts(v=>{const n=v-1;if(n<=0)setStatus('lost');return Math.max(0,n)})}next=setTimeout(prepare,Math.max(1800,2500-round*250))},1250)};next=setTimeout(prepare,3600);return()=>{active=false;clearTimeout(next);clearTimeout(strike);clearTimeout(clear)}},[status,round]);
 useEffect(()=>{const down=e=>{const d=e.key==='ArrowLeft'||e.key==='a'?-1:e.key==='ArrowRight'||e.key==='d'?1:0;if(d&&status==='playing'){e.preventDefault();setLane(v=>Math.max(0,Math.min(2,v+d)))}};addEventListener('keydown',down);return()=>removeEventListener('keydown',down)},[status]);
 const rotate=i=>status==='playing'&&setMirrors(a=>a.map((v,j)=>i===j?(v+1)%4:v));
 const fire=()=>{if(!aligned||status!=='playing')return;setFlash(true);setTimeout(()=>{setFlash(false);if(round===2)setStatus('won');else{setRound(v=>v+1);setMirrors([0,0,0,0])}},700)};
 const restart=()=>{attackRef.current=0;lockRef.current=0;setRound(0);setMirrors([0,0,0,0]);setLane(1);setHearts(3);setWarning(null);setImpact(null);setStatus('playing');setFlash(false);setAttacks(0)};
 const stars=status==='won'?1+(hearts===3?1:0)+(attacks<=12?1:0):0;
 useEffect(()=>{if(status!=='won')return;setSaved(cur=>{const n={...cur,41:{stars:Math.max(cur[41]?.stars||0,stars),crystal:1}};localStorage.setItem(KEY,JSON.stringify(n));return n})},[status,stars]);
 const totalStars=Object.values(saved).reduce((s,x)=>s+(x?.stars||0),0),totalCrystals=Object.values(saved).reduce((s,x)=>s+(x?.crystal||0),0);
 return <main><header><a className="brand" href="?view=map"><span>VALLE</span> ESMERALDA<small>UNA AVENTURA POR DESCUBRIR</small></a><div className="chapter"><span>CAPÍTULO 07 · FINAL</span><strong>{level.name}</strong></div><div className="inventory"><span>★ <b>{totalStars}</b></span><span>◆ <b>{totalCrystals}</b></span><span className="energy">{'♥'.repeat(hearts)+'♡'.repeat(3-hearts)}</span></div><HubLinks/></header>
 <section className="game dark-boss-game"><svg className="world dark-boss-world" viewBox="0 0 1200 720"><defs><radialGradient id="arena-floor"><stop stopColor="#354065"/><stop offset=".62" stopColor="#15162b"/><stop offset="1" stopColor="#070812"/></radialGradient><linearGradient id="light-beam"><stop stopColor="#8dfcff"/><stop offset=".5" stopColor="#fff0a0"/><stop offset="1" stopColor="#a878ff"/></linearGradient></defs><image href="./art/maze-world-advanced.webp" width="1200" height="720" preserveAspectRatio="xMidYMid slice"/><rect width="1200" height="720" fill="#02030bd9"/><ellipse cx="600" cy="420" rx="470" ry="260" fill="url(#arena-floor)" stroke="#a98bd0" strokeWidth="7"/><ellipse cx="600" cy="420" rx="410" ry="215" fill="none" stroke="#d3a957" strokeWidth="3" strokeDasharray="14 12"/>
 <g className={'shadow-boss'+(flash?' struck':'')}><image href="./art/shadow-guardian.webp" x="465" y="35" width="270" height="300"/><g className="boss-life" transform="translate(600 68)">{[0,1,2].map(i=><path key={i} transform={'translate('+((i-1)*34)+' 0)'} d="M0-11 10 0 0 11-10 0Z" className={i<3-round?'full':''}/>)}</g></g>
 <g className="circuit-instruction" transform="translate(600 325)"><rect x="-190" y="-28" width="380" height="56" rx="16"/><text y="-3" textAnchor="middle">HAZ AVANZAR LA LUZ POR LOS CUATRO ESPEJOS</text><text className="circuit-progress" y="19" textAnchor="middle">{'◆'.repeat(reached)+'◇'.repeat(4-reached)}</text></g>
 <polyline className="light-channel" points={asPoints(channel)}/><polyline className={'live-light-beam'+(aligned?' complete':'')} points={asPoints(beam)}/>{flash&&<polyline className="boss-light-beam" points={asPoints(channel)}/>}<g className="light-source" transform="translate(160 610)"><circle r="26"/><text y="7" textAnchor="middle">✦</text></g>
 {POINTS.map((p,i)=><g className={'boss-mirror'+(i<reached||aligned?' aligned':'')+(i===reached&&!aligned?' active':'')} transform={'translate('+p.x+' '+p.y+')'} key={p.x}><circle r="47"/><path d="M-34-7 34-7 28 7-28 7Z" transform={'rotate('+(mirrors[i]*45)+')'}/><text y="76" textAnchor="middle">{i+1}</text></g>)}
 {warning!==null&&<g className="shadow-warning" transform={'translate('+LANES[warning]+' 610)'}><ellipse rx="92" ry="34"/><text y="7" textAnchor="middle">¡MUÉVETE!</text></g>}{impact!==null&&<g className="shadow-impact" transform={'translate('+LANES[impact]+' 585)'}><path d="M-55 45Q0-175 55 45Z"/></g>}<ellipse className="boss-hero-shadow" cx={LANES[lane]} cy="660" rx="42" ry="11"/><image className="boss-hero" href={impact===lane?'./art/hero-hurt.webp':'./art/hero-dodge.webp'} x={LANES[lane]-48} y="558" width="96" height="108"/></svg>
 <div className="dark-boss-objective"><div><small>RONDA {round+1}/3 · CIRCUITO {reached}/4</small><strong>{aligned?'¡Circuito completo! Concentra la luz contra el Guardián.':'El haz se detuvo en el espejo '+(reached+1)+'. Gíralo y observa el recorrido.'}</strong></div><span>{'♥'.repeat(hearts)+'♡'.repeat(3-hearts)}</span></div>
 <div className="mirror-controls four-mirrors">{mirrors.map((v,i)=><button className={(i<reached||aligned?'ready ':'')+(i===reached&&!aligned?'current':'')} onClick={()=>rotate(i)} disabled={status!=='playing'} key={i}><small>ESPEJO {i+1}</small><b>{GLYPHS[v]}</b><span>{i<reached||aligned?'CONECTADO':i===reached?'HAZ AQUÍ':'SIN LUZ'}</span></button>)}<button className="fire-light" onClick={fire} disabled={!aligned||status!=='playing'}>✦ CONCENTRAR LUZ</button></div>
 <div className="boss-movement"><button onClick={()=>setLane(v=>Math.max(0,v-1))} disabled={lane===0||status!=='playing'}>◀ ATRÁS</button><span>ESQUIVA LAS SOMBRAS</span><button onClick={()=>setLane(v=>Math.min(2,v+1))} disabled={lane===2||status!=='playing'}>ADELANTE ▶</button></div>
 {status==='won'&&<div className="victory"><div className="win-star">{'★'.repeat(stars)}</div><small>MUNDO COMPLETADO</small><h1>¡La luz venció a la sombra!</h1><p>Construiste tres circuitos de cuatro espejos y derrotaste al Guardián.</p><div className="rewards">★ {stars} estrellas <span>◆ 1 cristal</span></div><button onClick={onNext}>Volver al mapa →</button></div>}{status==='lost'&&<div className="victory defeat"><div className="win-star">♡</div><small>LA SOMBRA TE ALCANZÓ</small><h1>El Guardián sigue en pie</h1><p>Observa el carril marcado y muévete antes del golpe.</p><button onClick={restart}>Reintentar ↻</button></div>}</section>
 <footer><div className="guide-icon">✧</div><p>Sigue el haz: cada espejo cambia físicamente su dirección. Completa el circuito y esquiva los ataques.</p><span className="attempts">Desafío final 5/5</span></footer></main>
}
