import React,{useEffect,useRef,useState} from 'react';
import {getLogicChallenges} from '../game/logicChallenges.js';
import HubLinks from './HubLinks.jsx';
import {MemoryRecoveryGate} from './PilotGates.jsx';
import {clearLogicFailures,recordLogicFailure,requiresLogicRecovery} from '../game/pilotAccess.js';
import {recordGameError} from '../game/progressTracking.js';

const ANSWER_X=[500,740,970],START_X=165,PROGRESS_KEY='valle-esmeralda-logic-progress';
const shuffled=values=>{const result=[...values];for(let index=result.length-1;index>0;index--){const other=Math.floor(Math.random()*(index+1));[result[index],result[other]]=[result[other],result[index]];}return result;};
const loadProgress=()=>{try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');}catch{return {};}};

export default function LogicLevel({level,levels,onSelectLevel,onNext,worldComplete=false}){
  const challenges=getLogicChallenges(level.id),[round,setRound]=useState(0),[order,setOrder]=useState([0,1,2,3]),[hearts,setHearts]=useState(1),[status,setStatus]=useState('playing');
  const [selection,setSelection]=useState(-1),[position,setPosition]=useState({x:START_X,jump:0}),[moving,setMoving]=useState(false),[mistakes,setMistakes]=useState(0),[moves,setMoves]=useState(0),[seconds,setSeconds]=useState(level.timeLimit||0),[menu,setMenu]=useState(false),[feedback,setFeedback]=useState(''),[saved,setSaved]=useState(loadProgress);
  const [recoveryRequired,setRecoveryRequired]=useState(requiresLogicRecovery),[showRecovery,setShowRecovery]=useState(requiresLogicRecovery);
  const question=challenges[order[0]], [answerOrder,setAnswerOrder]=useState(()=>shuffled(challenges[0].answers));
  const animation=useRef(0),delay=useRef(0);
  const prepare=answers=>{setSelection(-1);setPosition({x:START_X,jump:0});setMoving(false);setStatus('playing');setSeconds(level.timeLimit||0);setFeedback('');setAnswerOrder(shuffled(answers));};
  const restart=()=>{clearTimeout(delay.current);cancelAnimationFrame(animation.current);setRound(0);setOrder([0,1,2,3]);setHearts(1);setMistakes(0);setMoves(0);prepare(challenges[0].answers);};
  useEffect(restart,[level.id]);
  useEffect(()=>()=>{cancelAnimationFrame(animation.current);clearTimeout(delay.current);},[]);
  const fail=reason=>{if(status!=='playing')return;recordGameError(level.id);const remaining=hearts-1,nextOrder=[...order.slice(1),order[0]];setMistakes(value=>value+1);setHearts(remaining);setFeedback(reason==='time'?'Se terminó el tiempo.':`La regla no lleva a ${answerOrder[selection]}.`);setStatus(remaining?'wrong':'lost');if(remaining)delay.current=setTimeout(()=>{setOrder(nextOrder);prepare(challenges[nextOrder[0]].answers);},1750);else setRecoveryRequired(recordLogicFailure()>=2);};
  useEffect(()=>{if(!level.timeLimit||status!=='playing'||menu)return;const timer=setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer);},[level.id,level.timeLimit,status,round,menu]);
  useEffect(()=>{if(level.timeLimit&&seconds===0&&status==='playing')fail('time');},[seconds,status]);
  const move=delta=>{if(status!=='playing'||moving||menu)return;const next=selection<0?0:Math.max(0,Math.min(2,selection+delta));if(next===selection)return;const from=position.x,to=ANSWER_X[next],started=performance.now();setSelection(next);setMoving(true);setMoves(value=>value+1);
    const step=now=>{const progress=Math.min(1,(now-started)/520),ease=1-Math.pow(1-progress,3);setPosition({x:from+(to-from)*ease,jump:Math.sin(Math.PI*progress)*105});if(progress<1)animation.current=requestAnimationFrame(step);else setMoving(false);};animation.current=requestAnimationFrame(step);
  };
  const fall=()=>{const x=position.x,started=performance.now();setStatus('falling');setFeedback('¡La piedra cedió!');const step=now=>{const progress=Math.min(1,(now-started)/680);setPosition({x,jump:-390*progress*progress});if(progress<1)animation.current=requestAnimationFrame(step);else fail('answer');};animation.current=requestAnimationFrame(step);};
  const choose=()=>{if(status!=='playing'||moving||selection<0||menu)return;if(answerOrder[selection]!==question.correct){fall();return;}setStatus('correct');setFeedback(`¡Correcto! ${question.hint}`);delay.current=setTimeout(()=>{if(round===challenges.length-1){setStatus('won');return;}const nextOrder=order.slice(1);setRound(value=>value+1);setOrder(nextOrder);prepare(challenges[nextOrder[0]].answers);},1600);};
  useEffect(()=>{const key=e=>{if(e.key==='Escape'){setMenu(value=>!value);return;}if(menu)return;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a'){e.preventDefault();move(-1);}if(e.key==='ArrowRight'||e.key.toLowerCase()==='d'){e.preventDefault();move(1);}if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
  const stars=status==='won'?1+(mistakes===0?1:0)+(moves<=10?1:0):0;
  useEffect(()=>{if(status!=='won')return;clearLogicFailures();setRecoveryRequired(false);setSaved(current=>{const next={...current,[level.id]:{stars:Math.max(current[level.id]?.stars||0,stars),crystal:1}};localStorage.setItem(PROGRESS_KEY,JSON.stringify(next));return next;});},[status]);
  const logicLevels=levels.filter(item=>item.logic||item.coordinate||item.cannonCoordinate),totalStars=logicLevels.reduce((sum,item)=>sum+(saved[item.id]?.stars||0),0),totalCrystals=logicLevels.reduce((sum,item)=>sum+(saved[item.id]?.crystal||0),0),maxStars=logicLevels.length*3,maxCrystals=logicLevels.length;
  return <main><header><a className="brand" href="?view=map"><span>VALLE</span> ESMERALDA<small>UNA AVENTURA POR DESCUBRIR</small></a><div className="chapter"><span>CAPÍTULO 02</span><strong>{level.name}</strong></div><div className="inventory"><span>★ <b>{totalStars}</b><small>/ {maxStars}</small></span><span>◆ <b>{totalCrystals}</b><small>/ {maxCrystals}</small></span><span className="energy" aria-label={`${hearts} vida`}>{hearts?'♥':'♡'}</span></div><HubLinks/><button className="menu-button" onClick={()=>setMenu(true)}>☰</button></header>
    <section className="game logic-game" aria-label={`Nivel ${level.id}: ${level.name}`}><svg className="world logic-world" viewBox="0 0 1200 800" role="img" aria-label="Puente fantástico con tres respuestas posibles"><defs><filter id="choice-glow"><feGaussianBlur stdDeviation="7" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><image href="./art/logic-bridge.webp" width="1200" height="800" preserveAspectRatio="xMidYMid slice"/>
      <g className="logic-question"><rect x="315" y="35" width="570" height="128" rx="18"/><text x="600" y="70" className="logic-kicker">{level.logicKind.toUpperCase()} · DECISIÓN {round+1}/4</text><text x="600" y="126" className="logic-prompt">{question.prompt}</text></g>
      {level.timeLimit>0&&<g className={seconds<=5?'logic-timer urgent':'logic-timer'}><rect x="1025" y="35" width="125" height="70" rx="14"/><text x="1087" y="80">{seconds} s</text></g>}
      {answerOrder.map((answer,index)=><g key={answer} className={`answer-stone${selection===index?' selected':''}${status==='falling'&&selection===index?' falling':''}${status==='wrong'&&selection===index?' wrong':''}${status==='correct'&&selection===index?' correct':''}`} transform={`translate(${ANSWER_X[index]} 471)`} filter={selection===index?'url(#choice-glow)':undefined}><rect x="-65" y="-37" width="130" height="74" rx="12"/><text y="13" textAnchor="middle">{answer}</text>{selection===index&&<path d="m-13 53 13 13 13-13"/>}</g>)}
      <ellipse className="logic-hero-shadow" cx={position.x} cy="410" rx={Math.max(8,46-Math.abs(position.jump)*.12)} ry="10" opacity={status==='falling'?0:Math.max(.12,.65-position.jump*.004)}/><g className={status==='falling'?'logic-hero falling':status==='wrong'?'logic-hero hurt':'logic-hero'} transform={`translate(${position.x-68} ${258-position.jump})`}><image href={status==='wrong'?'./art/hero-hurt.webp':'./art/hero-dodge.webp'} width="136" height="150"/>{status==='wrong'&&<text className="logic-ouch" x="103" y="18">¡AUCH!</text>}</g>
      {feedback&&<g className={`logic-feedback ${status}`}><rect x="330" y="180" width="540" height="60" rx="14"/><text x="600" y="218" textAnchor="middle">{feedback}</text></g>}
    </svg>
    <div className="logic-controls"><div><strong>{selection<0?'EXPLORA LAS RESPUESTAS':`RESPUESTA SELECCIONADA: ${answerOrder[selection]}`}</strong><small>{status==='wrong'||status==='correct'?question.hint:'Muévete, compara la regla y confirma tu decisión.'}</small></div><div className="logic-buttons"><button onClick={()=>move(-1)} disabled={moving||status!=='playing'}>◀ ANTERIOR</button><button className="choose-answer" onClick={choose} disabled={moving||selection<0||status!=='playing'}>◆ ELEGIR</button><button onClick={()=>move(1)} disabled={moving||status!=='playing'}>SIGUIENTE ▶</button></div></div>
    {status==='won'&&<div className="victory"><div className="win-star">{'★'.repeat(stars)}</div><small>{worldComplete?'MUNDO COMPLETADO':'NIVEL COMPLETADO'}</small><h1>¡Reglas descubiertas!</h1><p>Resolviste las cuatro decisiones y tu progreso quedó guardado.</p><div className="rewards">★ {stars} estrellas <span>◆ 1 cristal</span></div><button onClick={onNext}>{worldComplete?'MUNDO COMPLETADO · VOLVER AL MAPA →':'Continuar →'}</button></div>}
    {status==='lost'&&<div className="victory defeat"><div className="win-star">♡</div><small>EL PUENTE SE HA CERRADO</small><h1>Revisa la regla</h1><p>{question.hint} Al reintentar, las respuestas cambiarán de posición.</p><button onClick={()=>recoveryRequired?setShowRecovery(true):restart()}>{recoveryRequired?'Recuperar el paso →':'Reintentar ↻'}</button></div>}
    {showRecovery&&<MemoryRecoveryGate onRecovered={()=>{setShowRecovery(false);setRecoveryRequired(false);restart();}}/>}
    {menu&&<div className="modal-backdrop"><section className="menu-card logic-map"><small>CAPÍTULO 02</small><h2>Mapa de los desafíos</h2><p>Tu progreso se conserva en este dispositivo.</p><button onClick={()=>setMenu(false)}>Continuar</button><div className="map-levels">{logicLevels.map(item=>{const index=levels.findIndex(candidate=>candidate.id===item.id),record=saved[item.id];return <button className={item.id===level.id?'map-current':'secondary'} key={item.id} onClick={()=>onSelectLevel(index)}><b>Nivel {item.id}</b><span>{record?'★'.repeat(record.stars):'○ Sin completar'}</span></button>;})}</div><button className="secondary" onClick={()=>onSelectLevel(0)}>Volver al Capítulo 1</button></section></div>}
    </section><footer><div className="guide-icon">✧</div><p>{status==='wrong'?`${question.hint} Ahora recibirás otro desafío.`:status==='correct'?question.hint:'Colócate frente a una respuesta y pulsa ELEGIR. La decisión solo cuenta al confirmarla.'}</p><span className="attempts">Una vida · Decisión {round+1}/4 · {level.timeLimit?`${seconds} s`:'Sin límite de tiempo'}</span></footer></main>;
}

