import React,{useEffect,useMemo,useState} from 'react';
import HubLinks from './HubLinks.jsx';
import {getMazeLevel,isMazeOpen} from '../game/mazeLevels.js';
import {recordGameError} from '../game/progressTracking.js';

const PROGRESS_KEY='valle-esmeralda-logic-progress',cellKey=point=>point.x+','+point.y,readProgress=()=>{try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');}catch{return {};}};

export default function MazeLevel({level,onNext}){
  const maze=useMemo(()=>getMazeLevel(level.id),[level.id]),[position,setPosition]=useState(maze.start),[collected,setCollected]=useState(new Set()),[status,setStatus]=useState('playing'),[feedback,setFeedback]=useState('Busca la salida'),[moves,setMoves]=useState(0),[bumps,setBumps]=useState(0),[seconds,setSeconds]=useState(maze.timeLimit||0),[menu,setMenu]=useState(false),[saved,setSaved]=useState(readProgress),[facing,setFacing]=useState(1),[rotation,setRotation]=useState(0),[turnIn,setTurnIn]=useState(maze.rotationInterval||0),[enemies,setEnemies]=useState(maze.enemies),[hearts,setHearts]=useState(3),[invulnerable,setInvulnerable]=useState(false),[lossReason,setLossReason]=useState('time'),[lightEnergy,setLightEnergy]=useState(100),[pulseTick,setPulseTick]=useState(0);
  const restart=()=>{setPosition(maze.start);setCollected(new Set());setStatus('playing');setFeedback('Busca la salida');setMoves(0);setBumps(0);setSeconds(maze.timeLimit||0);setMenu(false);setFacing(1);setRotation(0);setTurnIn(maze.rotationInterval||0);setEnemies(maze.enemies);setHearts(3);setInvulnerable(false);setLossReason('time');setLightEnergy(100);setPulseTick(0);};
  useEffect(restart,[maze]);
  useEffect(()=>{if(!maze.timeLimit||status!=='playing'||menu)return;const timer=setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer);},[maze.timeLimit,status,menu]);
  useEffect(()=>{if(maze.timeLimit&&seconds===0&&status==='playing'){recordGameError(level.id);setLossReason('time');setStatus('lost');}},[seconds,status,maze.timeLimit]);
  useEffect(()=>{if(!maze.rotating||status!=='playing'||menu)return;const timer=setInterval(()=>setTurnIn(value=>{if(value<=1){setRotation(current=>(current+1)%4);setFeedback('¡El laberinto giró! Adapta tu orientación');return maze.rotationInterval;}return value-1;}),1000);return()=>clearInterval(timer);},[maze,status,menu]);
  useEffect(()=>{if(!maze.enemyCount||status!=='playing'||menu)return;const timer=setInterval(()=>setEnemies(current=>current.map((enemy,index)=>{const options=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:enemy.x+dx,y:enemy.y+dy})).filter(point=>isMazeOpen(maze,point.x,point.y));options.sort((a,b)=>Math.abs(a.x-position.x)+Math.abs(a.y-position.y)-Math.abs(b.x-position.x)-Math.abs(b.y-position.y));const next=options[(enemy.tick+index)%3===0?Math.min(1,options.length-1):0]||enemy;return {...next,id:enemy.id,tick:enemy.tick+1};})),maze.enemySpeed);return()=>clearInterval(timer);},[maze,status,menu,position]);
  useEffect(()=>{if(invulnerable||status!=='playing'||!enemies.some(enemy=>cellKey(enemy)===cellKey(position)))return;recordGameError(level.id);setInvulnerable(true);setFeedback('¡Un guardián te alcanzó! Regresas al inicio');setPosition(maze.start);setHearts(value=>{const next=value-1;if(next<=0){setLossReason('enemy');setStatus('lost');}return Math.max(0,next);});},[enemies,position,invulnerable,status,maze.start]);
  useEffect(()=>{if(!invulnerable)return;const timer=setTimeout(()=>setInvulnerable(false),1400);return()=>clearTimeout(timer);},[invulnerable]);
  useEffect(()=>{if(!maze.pulse||status!=='playing'||menu)return;const timer=setInterval(()=>setPulseTick(value=>(value+1)%8),1000);return()=>clearInterval(timer);},[maze.pulse,status,menu]);
  const move=(screenX,screenY)=>{if(status!=='playing'||menu)return;if(screenX)setFacing(screenX>0?1:-1);const vectors=[[screenX,screenY],[screenY,-screenX],[-screenX,-screenY],[-screenY,screenX]],delta=vectors[rotation],target={x:position.x+delta[0],y:position.y+delta[1]};if(!isMazeOpen(maze,target.x,target.y)){recordGameError(level.id);setBumps(value=>value+1);setFeedback('Ese muro no tiene paso');return;}const nextCollected=new Set(collected),found=maze.keys.find(key=>cellKey(key)===cellKey(target)&&!collected.has(cellKey(key)));if(found){nextCollected.add(cellKey(found));setCollected(nextCollected);if(maze.lightDrain){setLightEnergy(100);setFeedback('¡Cristal encontrado! La linterna recuperó toda su luz');}else setFeedback('¡Llave de cristal encontrada!');}else setFeedback('Sigue explorando');if(maze.lightDrain&&!found)setLightEnergy(value=>Math.max(0,value-3));setPosition(target);setMoves(value=>value+1);if(cellKey(target)===cellKey(maze.exit)){if(nextCollected.size===maze.keys.length)setStatus('won');else{const left=maze.keys.length-nextCollected.size;setFeedback('El portal necesita '+left+' llave'+(left===1?'':'s')+' más');}}};
  useEffect(()=>{const commands={ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0],ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1]};const key=event=>{if(event.key==='Escape'){setMenu(value=>!value);return;}const command=commands[event.key]||commands[event.key.toLowerCase()];if(command){event.preventDefault();move(...command);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
  const stars=status==='won'?1+((maze.enemyCount?hearts===3:bumps===0)?1:0)+(moves<=maze.parMoves?1:0):0;
  useEffect(()=>{if(status!=='won')return;setSaved(current=>{const next={...current,[level.id]:{stars:Math.max(current[level.id]?.stars||0,stars),crystal:1}};localStorage.setItem(PROGRESS_KEY,JSON.stringify(next));return next;});},[status,level.id,stars]);
  const dark=Boolean(maze.dark),guardian=level.id>=32&&level.id<=36,advanced=level.id>=27&&!guardian&&!dark,worldNumber=dark?7:guardian?6:advanced?5:4,worldStep=dark?level.id-36:guardian?level.id-31:advanced?level.id-26:level.id-21,worldName=dark?'Galerías de la Penumbra':guardian?'Ciudadela Giratoria':advanced?'Fortaleza de los Enigmas':'Laberintos del Cielo',worldArt=guardian?'./art/maze-world-rotating.webp':advanced||dark?'./art/maze-world-advanced.webp':'./art/maze-world.webp';
  const totalStars=Object.values(saved).reduce((sum,item)=>sum+(item?.stars||0),0),totalCrystals=Object.values(saved).reduce((sum,item)=>sum+(item?.crystal||0),0),board=guardian?{x:340,y:140,w:520,h:520}:{x:118,y:154,w:964,h:474},cw=board.w/maze.width,ch=board.h/maze.height,center=point=>({x:board.x+(point.x+.5)*cw,y:board.y+(point.y+.5)*ch}),remaining=maze.keys.length-collected.size,mission=dark?(remaining?'Encuentra '+remaining+' cristal'+(remaining===1?'':'es')+' y busca la entrada':'La entrada ha quedado abierta'):remaining?'Encuentra '+remaining+' llave'+(remaining===1?'':'s')+' y llega al portal':'El camino al portal está abierto',mazeCenter={x:board.x+board.w/2,y:board.y+board.h/2},rawHero=center(position),angle=rotation*Math.PI/2,hero={x:mazeCenter.x+(rawHero.x-mazeCenter.x)*Math.cos(angle)-(rawHero.y-mazeCenter.y)*Math.sin(angle),y:mazeCenter.y+(rawHero.x-mazeCenter.x)*Math.sin(angle)+(rawHero.y-mazeCenter.y)*Math.cos(angle)},heroWidth=Math.max(48,Math.min(66,cw*1.05)),heroHeight=Math.max(56,Math.min(76,ch*1.2)),worldTotal=5,effectiveLightRadius=maze.pulse?(pulseTick<2?270:82):maze.lightDrain?Math.max(44,(maze.lightRadius||130)*(lightEnergy/100)):maze.lightRadius||118;
  return <main><header><a className="brand" href="?view=map"><span>VALLE</span> ESMERALDA<small>UNA AVENTURA POR DESCUBRIR</small></a><div className="chapter"><span>CAPÍTULO {worldNumber.toString().padStart(2,'0')}</span><strong>{level.name}</strong></div><div className="inventory"><span>★ <b>{totalStars}</b></span><span>◆ <b>{totalCrystals}</b></span><span className="energy" aria-label={maze.timeLimit?seconds+' segundos':'Sin límite de tiempo'}>{maze.timeLimit?seconds+'s':'∞'}</span></div><HubLinks/><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Abrir menú">☰</button></header>
  <section className={'game maze-game'+(advanced?' maze-advanced':'')+(guardian?' maze-guardian':'')+(dark?' maze-dark':'')} aria-label={'Nivel '+level.id+': '+level.name}><svg className="world maze-world" viewBox="0 0 1200 800" role="img" aria-label="Laberinto fantástico de piedra"><defs><linearGradient id="maze-stone" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={guardian?'#5e557d':advanced||dark?'#715838':'#426254'}/><stop offset=".48" stopColor={guardian?'#393752':advanced||dark?'#493d34':'#274a43'}/><stop offset="1" stopColor={guardian?'#1c2638':advanced||dark?'#242932':'#142f31'}/></linearGradient><radialGradient id="flashlight-cutout"><stop offset="0" stopColor="black"/><stop offset=".62" stopColor="black"/><stop offset="1" stopColor="white"/></radialGradient><mask id="darkness-mask"><rect width="1200" height="800" fill="white"/><circle cx={hero.x} cy={hero.y} r={effectiveLightRadius} fill="url(#flashlight-cutout)"/></mask></defs><image href={worldArt} width="1200" height="800" preserveAspectRatio="xMidYMid slice"/>{guardian?<circle className="maze-veil maze-round-veil" cx={mazeCenter.x} cy={mazeCenter.y} r="278"/>:<rect className="maze-veil" x={board.x} y={board.y} width={board.w} height={board.h} rx="18"/>}{guardian&&<circle className="maze-turn-ring" cx={mazeCenter.x} cy={mazeCenter.y} r="270"/>}
  <g className="maze-rotor" transform={'rotate('+(rotation*90)+' '+mazeCenter.x+' '+mazeCenter.y+')'}><g className="maze-grid">{maze.grid.flatMap((row,y)=>row.map((cell,x)=>cell==='#'?<rect key={x+'-'+y} x={board.x+x*cw} y={board.y+y*ch} width={cw+1} height={ch+1} rx={Math.min(5,cw*.12)}/>:null))}</g>
  <g className={'maze-exit '+(remaining?'locked':'')} transform={'translate('+center(maze.exit).x+' '+center(maze.exit).y+')'}><circle r={Math.min(cw,ch)*.38}/><text y="8" textAnchor="middle">{remaining?'◇':'◆'}</text></g>
  {maze.keys.map((key,index)=>!collected.has(cellKey(key))&&<g className="maze-key" key={cellKey(key)} transform={'translate('+center(key).x+' '+center(key).y+')'}><circle r={Math.min(cw,ch)*.29}/><text y="7" textAnchor="middle">✦</text><title>{'Llave '+(index+1)}</title></g>)}
  {enemies.map(enemy=>{const spot=center(enemy),visible=!dark||Math.hypot(spot.x-hero.x,spot.y-hero.y)<effectiveLightRadius*1.2;return <g className="maze-enemy" opacity={visible?1:.03} key={enemy.id} transform={'translate('+spot.x+' '+spot.y+')'}><circle className="enemy-aura" r={Math.max(10,Math.min(cw,ch)*.42)}/><path d="M-8 7Q0-13 8 7Z"/><circle cx="-3" cy="0" r="1.6"/><circle cx="3" cy="0" r="1.6"/></g>;})}</g>
  <ellipse className="maze-hero-shadow" cx={hero.x} cy={hero.y+Math.min(18,ch*.25)} rx={Math.max(14,Math.min(24,cw*.3))} ry="6"/><g className={'maze-hero'+(invulnerable?' hurt':'')} transform={'translate('+(hero.x-heroWidth/2)+' '+(hero.y-heroHeight*.68)+')'}><image href={invulnerable?'./art/hero-hurt.webp':'./art/hero-dodge.webp'} width={heroWidth} height={heroHeight} transform={facing<0?'translate('+heroWidth+' 0) scale(-1 1)':undefined} preserveAspectRatio="xMidYMax meet"/></g>{dark&&<><rect className="maze-darkness" width="1200" height="800" mask="url(#darkness-mask)"/><circle className="flashlight-rim" cx={hero.x} cy={hero.y} r={effectiveLightRadius*.72}/></>}
  <g className="maze-mission"><rect x="265" y="28" width="670" height="102" rx="18"/><text x="600" y="61" textAnchor="middle">{'LABERINTO '+worldStep+'/'+worldTotal+' · '+maze.width+' × '+maze.height+(maze.rotating?' · GIRA EN '+turnIn+' s':'')}</text><text className="maze-title" x="600" y="99" textAnchor="middle">{mission}</text></g></svg>
  <div className="maze-objectives"><span className={status==='won'?'done':''}>{dark?'★ ENCONTRAR LA ENTRADA':'★ ENCONTRAR LA SALIDA'}</span><span className={(maze.enemyCount?hearts===3:bumps===0)?'active':''}>{maze.enemyCount?'★ SIN QUE TE ATRAPEN':'★ SIN CHOCAR MUROS'}</span><span className={moves<=maze.parMoves?'active':''}>★ RUTA ÁGIL</span></div>
  <div className="maze-controls"><div><strong>{feedback}</strong><small>{maze.keys.length?(dark?'Cristales ':'Llaves ')+collected.size+'/'+maze.keys.length:'Observa los caminos antes de avanzar'} · Pasos {moves}</small>{maze.lightDrain&&<span className="lantern-energy">LUZ <i style={{width:lightEnergy+'%'}}/></span>}{maze.pulse&&<span className="pulse-status">{pulseTick<2?'✦ PULSO DE LUZ':'PRÓXIMO PULSO: '+(8-pulseTick)+' s'}</span>}</div>{maze.enemyCount&&<b className="maze-lives">{'♥'.repeat(hearts)+'♡'.repeat(3-hearts)}</b>}<div className="maze-pad"><button onClick={()=>move(0,-1)} disabled={status!=='playing'||menu} aria-label="Avanzar hacia arriba">▲</button><button onClick={()=>move(-1,0)} disabled={status!=='playing'||menu} aria-label="Avanzar hacia la izquierda">◀</button><button className="maze-center" disabled aria-label="Posición del explorador">◆</button><button onClick={()=>move(1,0)} disabled={status!=='playing'||menu} aria-label="Avanzar hacia la derecha">▶</button><button onClick={()=>move(0,1)} disabled={status!=='playing'||menu} aria-label="Avanzar hacia abajo">▼</button></div></div>
  {status==='won'&&<div className="victory"><div className="win-star">{'★'.repeat(stars)}</div><small>LABERINTO SUPERADO</small><h1>{dark?'¡Encontraste la entrada!':'¡Encontraste la salida!'}</h1><p>Recorriste el laberinto en {moves} pasos y abriste el portal.</p><div className="rewards">★ {stars} estrellas <span>◆ 1 cristal</span></div><button onClick={onNext}>{level.id<40?'Siguiente laberinto →':dark?'Enfrentar al Guardián →':'Volver al mapa →'}</button></div>}
  {status==='lost'&&<div className="victory defeat"><div className="win-star">{lossReason==='enemy'?'♡':'⌛'}</div><small>EL PORTAL SE HA CERRADO</small><h1>{lossReason==='enemy'?'Los guardianes te atraparon':'Se terminó el tiempo'}</h1><p>Recuerda los callejones y prueba una ruta más directa.</p><button onClick={restart}>Reintentar ↻</button></div>}
  {menu&&<div className="modal-backdrop"><section className="menu-card" role="dialog" aria-modal="true"><small>{worldName.toUpperCase()}</small><h2>Pausa de exploración</h2><p>Las flechas y WASD también controlan al protagonista.</p><button onClick={()=>setMenu(false)}>Continuar</button><button className="secondary" onClick={restart}>Reiniciar laberinto</button><a className="menu-link" href={'?view=world&world='+worldNumber}>Volver al mundo</a></section></div>}</section><footer><div className="guide-icon">✧</div><p>{dark?'La linterna revela solo una parte del camino. Avanza con cuidado hasta encontrar la entrada.':'Explora, recuerda los callejones y recoge todas las llaves antes de entrar al portal.'}</p><span className="attempts">Nivel de laberinto {worldStep}/{worldTotal}</span></footer></main>;
}

