import React,{useEffect,useRef,useState} from 'react';
import HubLinks from './HubLinks.jsx';
import {canKickStone} from '../game/pythagorean.js';
import {recordGameError} from '../game/progressTracking.js';

const fresh=()=>({x:150,vx:0,facing:1,jump:0,vy:0,run:0,rocks:[],spawn:.55,elapsed:0,id:1,invulnerable:0});
const BOSS_MAX_HEALTH=16;
const PLAYER_MAX_HEALTH=2;

export default function PythagoreanBossLevel(){
 const params=new URLSearchParams(location.search),finalTest=params.get('finalTest')==='1',showFinal=params.get('showFinal')==='1',startingBossHealth=showFinal?0:finalTest?3:BOSS_MAX_HEALTH;
 const [phase,setPhase]=useState(showFinal?'won':'dodge'),[view,setView]=useState(fresh),[hearts,setHearts]=useState(PLAYER_MAX_HEALTH),[bossMood,setBossMood]=useState(showFinal?'defeated':'idle'),[bossStage,setBossStage]=useState(finalTest||showFinal?2:0),[bossHealth,setBossHealth]=useState(startingBossHealth);
 const [attackStone,setAttackStone]=useState(null),[flyingStone,setFlyingStone]=useState(null),[heartPickup,setHeartPickup]=useState(null),[kicking,setKicking]=useState(false),[celebrating,setCelebrating]=useState(false),[message,setMessage]=useState('Esquiva las rocas y observa cómo ataca el Coloso.');
 const motion=useRef(fresh()),keys=useRef({left:false,right:false}),phaseRef=useRef(phase),stageRef=useRef(bossStage),bossHealthRef=useRef(startingBossHealth),heartsRef=useRef(PLAYER_MAX_HEALTH),stoneRef=useRef(null),heartRef=useRef(null),finalWaveRef=useRef(0),finalCalmRef=useRef(0),kickingRef=useRef(false),raf=useRef(0),timers=useRef(new Set());
 phaseRef.current=phase;stageRef.current=bossStage;
 const introDuration=finalTest?1.5:7;
 const later=(fn,ms)=>{const id=setTimeout(()=>{timers.current.delete(id);fn();},ms);timers.current.add(id);};
 const save=()=>{try{const key='valle-esmeralda-logic-progress',progress=JSON.parse(localStorage.getItem(key)||'{}');localStorage.setItem(key,JSON.stringify({...progress,68:{stars:3,crystal:1,complete:true}}));}catch{}};
 const hurt=()=>{const state=motion.current;if(state.invulnerable>0||phaseRef.current==='lost')return;recordGameError(68);state.invulnerable=1.15;setBossMood('pleased');setHearts(value=>{const next=Math.max(0,value-1);heartsRef.current=next;if(next<=0){phaseRef.current='lost';setPhase('lost');stoneRef.current=null;heartRef.current=null;setAttackStone(null);setHeartPickup(null);setMessage('El Coloso cerró las ruinas. Vuelve a estudiar su patrón.');}return next;});later(()=>setBossMood('idle'),700);};
 const jump=()=>{const state=motion.current;if(state.jump<2&&phaseRef.current!=='won'&&phaseRef.current!=='lost'){state.jump=.01;state.vy=620;setView({...state,rocks:state.rocks.map(rock=>({...rock}))});setMessage('¡Buen salto! Sigue moviéndote antes del siguiente impacto.');}};
 const placeCounterStone=()=>{if(phaseRef.current!=='fight'||stoneRef.current||performance.now()<finalWaveRef.current)return;const positions=[250,430,320,535,390],hitCount=BOSS_MAX_HEALTH-bossHealthRef.current,stone={x:positions[hitCount%positions.length],id:Date.now(),fading:false};stoneRef.current=stone;setAttackStone(stone);setMessage('¡Hay una piedra en el puente! Acércate y patéala hacia el Coloso.');later(()=>{if(stoneRef.current?.id!==stone.id)return;stoneRef.current={...stone,fading:true};setAttackStone({...stone,fading:true});},6000);later(()=>{if(stoneRef.current?.id!==stone.id)return;stoneRef.current=null;setAttackStone(null);setMessage('La piedra se desvaneció. Pronto aparecerá otra.');later(placeCounterStone,700);},7400);};
 const kickStone=()=>{
  if(phaseRef.current!=='fight'||kickingRef.current)return;const stone=stoneRef.current,state=motion.current;if(!stone)return;
  if(!canKickStone(state.x,stone.x,state.facing)){setMessage(Math.abs(state.x-stone.x)>72?'Acércate más a la piedra para poder patearla.':'Colócate detrás de la piedra y mira hacia el Coloso.');return;}
  kickingRef.current=true;state.invulnerable=Math.max(state.invulnerable,1.2);setKicking(true);setBossMood('attacking');setFlyingStone({x:stone.x,id:Date.now()});stoneRef.current=null;setAttackStone(null);
  later(()=>{setFlyingStone(null);setBossMood('hurt');kickingRef.current=false;setKicking(false);const remaining=bossHealthRef.current-1;bossHealthRef.current=remaining;setBossHealth(remaining);
   if(remaining<=0){phaseRef.current='ending';setPhase('ending');motion.current.rocks=[];stoneRef.current=null;heartRef.current=null;setAttackStone(null);setHeartPickup(null);setBossMood('defeated');setCelebrating(true);setMessage('¡Impacto final! El poder del Coloso regresa al Valle Esmeralda.');save();later(()=>{phaseRef.current='won';setPhase('won');},4200);return;}
   if(remaining===8){const pickup={x:Math.max(170,Math.min(600,state.x+145)),id:Date.now(),fading:false};heartRef.current=pickup;setHeartPickup(pickup);setMessage('¡El Coloso está a la mitad! Tienes 10 segundos para recoger el corazón.');later(()=>{if(heartRef.current?.id!==pickup.id)return;heartRef.current={...pickup,fading:true};setHeartPickup({...pickup,fading:true});},8500);later(()=>{if(heartRef.current?.id!==pickup.id)return;heartRef.current=null;setHeartPickup(null);setMessage('El corazón se desvaneció. Mantente alerta.');},10000);}
   const nextStage=remaining<=4?2:remaining<=10?1:0;if(nextStage!==stageRef.current){stageRef.current=nextStage;setBossStage(nextStage);setMessage(nextStage===2?'¡Está casi vencido! El Coloso desata una lluvia de piedras.':'El Coloso se enfurece: las piedras caerán con mayor velocidad.');}
   if(remaining===2){finalWaveRef.current=performance.now()+4200;setBossMood('attacking');setMessage('¡Última prueba! Resiste la oleada y espera el momento de calma.');later(()=>{if(phaseRef.current!=='fight'||bossHealthRef.current!==2)return;finalWaveRef.current=0;finalCalmRef.current=performance.now()+3000;motion.current.spawn=.9;setBossMood('hurt');setMessage('¡La tormenta cedió! Aprovecha ahora para contraatacar.');placeCounterStone();},4200);}else later(()=>{setBossMood('angry');placeCounterStone();},650);
  },1150);
 };

 useEffect(()=>{
  let last=performance.now();const tick=now=>{const dt=Math.min(.1,(now-last)/1000);last=now;const state=motion.current,direction=(keys.current.right?1:0)-(keys.current.left?1:0),target=direction*440,diff=target-state.vx;
   const airborne=state.jump>0||state.vy>0,acceleration=(direction?1750:airborne?180:2250)*dt;state.vx+=Math.sign(diff)*Math.min(Math.abs(diff),acceleration);state.x+=state.vx*dt;if(state.x<72||state.x>715){state.x=Math.max(72,Math.min(715,state.x));state.vx=0;}if(direction)state.facing=direction;state.run+=Math.abs(state.vx)*dt/34;state.invulnerable=Math.max(0,state.invulnerable-dt);
   if(state.jump>0||state.vy>0){state.jump+=state.vy*dt;state.vy-=1250*dt;if(state.jump<=0){state.jump=0;state.vy=0;}}
   if(phaseRef.current==='dodge'||phaseRef.current==='fight'){state.elapsed+=dt;state.spawn-=dt;
    if(state.spawn<=0){const stage=stageRef.current,progress=Math.min(1,state.elapsed/18),nowTime=performance.now(),finalWave=nowTime<finalWaveRef.current,finalCalm=nowTime<finalCalmRef.current,makeRock=x=>{const r=22+Math.random()*19;return{id:state.id++,x,y:-50,r,vy:155+progress*145+stage*70+(finalWave?38:0)+Math.random()*65,spin:(Math.random()-.5)*(230+stage*65),rotation:Math.random()*360};},x=90+Math.random()*625;state.rocks.push(makeRock(x));if(!finalCalm&&stage===2&&Math.random()<(finalWave ? .68 : .52))state.rocks.push(makeRock(x<400?x+210:x-210));state.spawn=finalWave ? .38+Math.random()*.16 : finalCalm ? 1.15+Math.random()*.2 : Math.max(.3,.84-progress*.2-stage*.14+Math.random()*.22);setBossMood('attacking');later(()=>setBossMood('idle'),460);}
    for(const rock of state.rocks){rock.vy+=210*dt;rock.y+=rock.vy*dt;rock.rotation+=rock.spin*dt;const heroY=420-state.jump;if(state.invulnerable<=0&&Math.hypot(rock.x-state.x,rock.y-heroY)<rock.r+28){rock.y=700;hurt();}}
    state.rocks=state.rocks.filter(rock=>rock.y-rock.r<510);
    if(phaseRef.current==='fight'){const pickup=heartRef.current;if(pickup&&heartsRef.current<PLAYER_MAX_HEALTH&&Math.abs(pickup.x-state.x)<42&&state.jump<75){heartRef.current=null;setHeartPickup(null);setHearts(value=>{const next=Math.min(PLAYER_MAX_HEALTH,value+1);heartsRef.current=next;return next;});setMessage('¡Corazón recuperado! Continúa el combate.');}}
    if(phaseRef.current==='dodge'&&state.elapsed>=introDuration){phaseRef.current='fight';setPhase('fight');setBossMood('angry');placeCounterStone();}}
   setView({...state,rocks:state.rocks.map(rock=>({...rock}))});raf.current=requestAnimationFrame(tick);
  };raf.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf.current);
 },[]);
 const contextualAction=()=>{const stone=stoneRef.current,state=motion.current;stone&&canKickStone(state.x,stone.x,state.facing)?kickStone():jump();};
 useEffect(()=>{const down=e=>{if(e.key==='ArrowLeft'||e.key==='a'){e.preventDefault();keys.current.left=true;}if(e.key==='ArrowRight'||e.key==='d'){e.preventDefault();keys.current.right=true;}if((e.key==='ArrowUp'||e.key==='w'||e.key===' ')&&!e.repeat){e.preventDefault();contextualAction();}};const up=e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.current.left=false;if(e.key==='ArrowRight'||e.key==='d')keys.current.right=false;};const stop=()=>{keys.current={left:false,right:false};};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',stop);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',stop);for(const id of timers.current)clearTimeout(id);};},[]);
 const walking=Math.abs(view.vx)>25,frame=Math.floor(view.run)%2,stoneReady=attackStone&&canKickStone(view.x,attackStone.x,view.facing),jumpTilt=view.vy>40?-7:view.vy<-40?7:0;
 return <main className="pyth-page"><header><a className="brand" href="?view=map"><span>VALLE</span> ESMERALDA<small>UNA AVENTURA POR DESCUBRIR</small></a><div className="chapter"><span>RUINAS PITAGÓRICAS · NIVEL FINAL</span><strong>El Guardián de los Mundos</strong></div><div className="inventory"><span>★ <b>{phase==='won'?3:0}</b><small>/ 3</small></span><span>◆ <b>{phase==='won'?1:0}</b><small>/ 1</small></span><span className="energy" aria-label={`Vidas del protagonista: ${hearts} de ${PLAYER_MAX_HEALTH}`}>{Array.from({length:PLAYER_MAX_HEALTH},(_,i)=>i<hearts?'♥':'♡').join(' ')}</span></div><HubLinks/></header>
  <section className={`pyth-game boss-stage-${bossStage}${phase==='ending'?' final-collapse':''}`}><img className="pyth-bg" src="./art/pythagorean-ruins-arena.webp" alt="Ruinas elevadas sobre el Valle Esmeralda durante una tormenta"/><div className={`colossus ${bossMood}`}><img src="./art/emerald-colossus.webp" alt="Gran Coloso de piedra con un cristal esmeralda en la corona"/><i/></div><div className="colossus-health boss-life" aria-label={`Vida del Coloso: ${bossHealth} de ${BOSS_MAX_HEALTH}`}><small>VIDA DEL COLOSO</small><div><b style={{width:`${bossHealth/BOSS_MAX_HEALTH*100}%`}}/></div><strong>{bossHealth}/{BOSS_MAX_HEALTH}</strong></div>
   {flyingStone&&<div className="kicked-rock-flight" style={{'--flight-start':`${flyingStone.x/10}%`}} aria-label="Piedra pateada volando hacia el Coloso"><i/><b/><em/></div>}
   {view.rocks.map(rock=><div className="colossus-rock" key={rock.id} style={{left:`${rock.x/10}%`,top:`${rock.y/6}%`,width:rock.r*2,height:rock.r*2,transform:`translate(-50%,-50%) rotate(${rock.rotation}deg)`}}><i/></div>)}
   {heartPickup&&<div className={`boss-heart-pickup midpoint-heart${heartPickup.fading?' fading':''}`} style={{left:`${heartPickup.x/10}%`}} aria-label="Corazón de recuperación">♥</div>}
   {attackStone&&<button className={`counter-stone${stoneReady?' ready':''}${attackStone.fading?' fading':''}`} style={{left:`${attackStone.x/10}%`}} onClick={kickStone} aria-label="Patear la piedra hacia el Coloso"><i/><small>{stoneReady?'¡PATEA!':'ACÉRCATE'}</small></button>}
   <div className="pyth-hero-shadow" style={{left:`${view.x/10}%`,width:`${Math.max(34,64-view.jump*.18)}px`,opacity:Math.max(.2,.68-view.jump*.003)}}/>{walking&&view.jump===0&&<div className="pyth-run-dust" style={{left:`${view.x/10}%`}}/>}<div className={`pyth-hero${walking?' walking':''}${view.jump>0?' jumping':''}${view.vy>40?' ascending':view.vy<-40?' descending':''}${view.invulnerable>0?' hurt':''}${kicking?' kicking':''}${celebrating?' celebrating':''}`} style={{left:`${view.x/10}%`,bottom:`calc(27% + ${view.jump/6}%)`,'--face':view.facing,'--jump-tilt':`${jumpTilt}deg`,'--lean':`${Math.max(-6,Math.min(6,view.vx/65))}deg`}}><img src={celebrating?'./art/hero-dodge-game.webp':view.invulnerable>0?'./art/hero-hurt-game.webp':view.jump>0?'./art/hero-dodge-game.webp':`./art/hero-walk-side-${frame+1}-game.webp`} alt="Protagonista"/></div>
   {phase==='ending'&&<><div className="finale-energy-ring" aria-hidden="true"/><div className="boss-collapse-pieces" aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i} style={{'--piece':i}}/>)}</div><div className="finale-title"><small>EL ÚLTIMO GUARDIÁN HA CAÍDO</small><strong>EL VALLE VUELVE A BRILLAR</strong></div></>}
   <div className="pyth-mission"><small>{phase==='dodge'?`DESPIERTA AL GUARDIÁN · ${Math.max(0,introDuration-Math.floor(view.elapsed))} s`:phase==='fight'?`COMBATE · ${BOSS_MAX_HEALTH-bossHealth}/${BOSS_MAX_HEALTH} IMPACTOS`:phase==='ending'?'IMPACTO FINAL':phase==='won'?'RUINAS LIBERADAS':'EL COLOSO VENCIÓ'}</small><strong>{phase==='dodge'?'SOBREVIVE AL PRIMER ATAQUE':phase==='fight'?'ESQUIVA Y CONTRAATACA':phase==='ending'?'¡EL COLOSO SE DERRUMBA!':phase==='won'?'¡VICTORIA!':'VUELVE A INTENTARLO'}</strong></div>
   <div className="pyth-feedback">{message}</div>
   {(phase==='dodge'||phase==='fight')&&<div className="pyth-controls"><button onPointerDown={()=>keys.current.left=true} onPointerUp={()=>keys.current.left=false} onPointerLeave={()=>keys.current.left=false}>◀</button><button className={stoneReady?'kick-stone-button':''} onPointerDown={e=>{e.preventDefault();contextualAction();}}>{stoneReady?'⚡ PATEAR':'▲ SALTAR'}</button><button onPointerDown={()=>keys.current.right=true} onPointerUp={()=>keys.current.right=false} onPointerLeave={()=>keys.current.right=false}>▶</button></div>}
   {phase==='won'&&<div className="victory final-victory"><div className="victory-fireworks" aria-hidden="true">{Array.from({length:5},(_,i)=><i key={i} style={{'--burst':i}}/>)}</div><div className="win-star">★★★</div><small>FINAL PROVISIONAL COMPLETADO</small><h1>¡El Valle vuelve a brillar!</h1><div className="final-teacher"><div className="final-dani-avatar"><img src="./art/profe-dani-shop-v7.png" alt="Profe Dani B entrando para felicitar al protagonista"/><i aria-hidden="true"/></div><div className="final-dani-dialogue"><strong>Profe Dani B</strong><p className="dani-line line-one">¡Lo lograste! Observaste, razonaste y encontraste el momento preciso.</p><p className="dani-line line-two">También seguiste adelante después de cada intento. Esa resiliencia te permitió superar el desafío.</p><p className="dani-line line-three">Querer comprender y volver a intentarlo es una parte esencial del pensamiento matemático. ¡Felicitaciones!</p></div></div><div className="rewards">★ 3 estrellas <span>◆ 1 cristal</span></div><button onClick={()=>location.href='?view=map'}>Regresar al Valle Esmeralda</button></div>}
   {phase==='lost'&&<div className="victory defeat"><div className="win-star">♡</div><small>LAS RUINAS SIGUEN CERRADAS</small><h1>El Coloso resistió</h1><p>Muévete antes de que caiga cada roca y guarda vidas para los ataques más agresivos.</p><button onClick={()=>location.reload()}>Reintentar ↻</button></div>}
  </section><footer><div className="guide-icon">✦</div><p>Esquiva las rocas; al quedar frente a una piedra, el mismo control sirve para patearla.</p><span className="attempts">Flechas/WASD · Espacio: saltar o patear</span></footer></main>;
}

