import React,{useEffect,useMemo,useState} from 'react';
import {supabaseClient} from '../game/supabaseAuth.js';
import {syncProgressNow} from '../game/progressTracking.js';
import {currentStudentRank,displayedRank,isCurrentStudent,sortLeaderboard} from '../game/leaderboard.js';

export default function StudentLeaderboard({user,onClose}){
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');if(!supabaseClient){setError('La clasificación necesita conexión a internet.');setLoading(false);return;}await syncProgressNow();const result=await supabaseClient.rpc('leaderboard');if(result.error)setError('No fue posible cargar la clasificación. Inténtalo nuevamente.');else setRows(sortLeaderboard((result.data||[]).filter(row=>String(row.course||'').toUpperCase()!=='ADMIN')));setLoading(false);};
  useEffect(()=>{load();const key=event=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  const rank=useMemo(()=>currentStudentRank(rows,user),[rows,user]);
  return <div className="student-ranking-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="student-ranking" role="dialog" aria-modal="true" aria-labelledby="student-ranking-title"><header><div><small>EXPLORADORES DEL VALLE</small><h2 id="student-ranking-title">Ranking de estudiantes</h2></div><button autoFocus aria-label="Cerrar ranking" onClick={onClose}>×</button></header>{rank&&<div className="student-own-rank"><span>TU POSICIÓN</span><strong>#{rank}</strong><small>de {rows.length} exploradores</small></div>}<p className="ranking-rule">El puesto depende únicamente del avance. Quienes tienen el mismo porcentaje comparten posición.</p>{loading&&<p className="ranking-message">Actualizando tu avance…</p>}{error&&<div className="ranking-message error"><p>{error}</p><button onClick={load}>REINTENTAR</button></div>}{!loading&&!error&&!rows.length&&<p className="ranking-message">Todavía no hay resultados para mostrar.</p>}{!!rows.length&&<div className="student-ranking-list"><div className="ranking-row ranking-head"><span>Puesto</span><span>Explorador</span><span>Avance</span></div>{rows.map((row,index)=><div className={`ranking-row${isCurrentStudent(row,user)?' is-current':''}`} key={`${row.first_name}-${row.last_initial}-${row.course}-${index}`}><strong>#{displayedRank(rows,index)}</strong><span><b>{row.first_name} {row.last_initial}</b><small>{row.course}</small></span><b>{row.completion_percent}%</b></div>)}</div>}<footer><small>Solo se muestra el nombre, la inicial del apellido, el curso y el avance.</small><button onClick={load} disabled={loading}>↻ ACTUALIZAR</button></footer></section></div>;
}

