import React,{useEffect,useMemo,useRef,useState} from 'react';
import HubLinks from './HubLinks.jsx';
import {WAVE_LEVELS,matchesWave,wavePath,waveY} from '../game/waveChallenges.js';
import {recordGameError} from '../game/progressTracking.js';

const PROGRESS_KEY='valle-esmeralda-logic-progress',AMPLITUDES=[50,90,130],PHASES=['0','π/2','π','3π/2'];
const readProgress=()=>{try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');}catch{return {};}};

export default function WaveLevel({level,onNext,worldComplete=false}){
 const data=WAVE_LEVELS[level.id], [round,setRound]=useState(0),[choice,setChoice]=useState({a:90,b:1,p:0,f:'sin'}),[status,setStatus]=useState('aim'),[orb,setOrb]=useState(null),[hearts,setHearts]=useState(2),[mistakes,setMistakes]=useState(0),[seconds,setSeconds]=useState(data.time||0),animation=useRef(0);
 const target=data.rounds[round],showFrequency=level.id>=48,showPhase=level.id>=49,showFamily=level.id>=50;
 const checkpoints=useMemo(()=>[.24,.52,.8].map(t=>({x:110+t*1000,y:waveY(t*1000,target)})),[target]);
 useEffect(()=>{setRound(0);setChoice({a:90,b:1,p:0,f:'sin'});setStatus('aim');setHearts(2);setMistakes(0);setSeconds(data.time||0);},[level.id]);
 useEffect(()=>{if(!data.time||status==='won'||status==='lost')return;const timer=setInterval(()=>setSeconds(value=>{if(value<=1){recordGameError(level.id);setStatus('lost');return 0;}return value-1;}),1000);return()=>clearInterval(timer);},[data.time,status]);
 useEffect(()=>()=>cancelAnimationFrame(animation.current),[]);
 const set=(key,value)=>status==='aim'&&setChoice(current=>({...current,[key]:value}));
 function launch(){if(status!=='aim')return;setStatus('flying');const start=performance.now();const tick=now=>{const t=Math.min(1,(now-start)/1500),x=t*1000;setOrb({x:110+x,y:waveY(x,choice)});if(t<1){animation.current=requestAnimationFrame(tick);return;}if(matchesWave(choice,target)){setStatus('correct');setTimeout(()=>{if(round===data.rounds.length-1){setStatus('won');const progress=readProgress(),stars=1+(mistakes===0?1:0)+(hearts===2?1:0);localStorage.setItem(PROGRESS_KEY,JSON.stringify({...progress,[level.id]:{stars,crystal:1}}));}else{setRound(value=>value+1);setStatus('aim');setOrb(null);}},1200);}else{recordGameError(level.id);setMistakes(value=>value+1);setHearts(value=>{const next=value-1;if(next<=0)setStatus('lost');else setTimeout(()=>{setStatus('aim');setOrb(null);},1400);return Math.max(0,next);});}};animation.current=requestAnimationFrame(tick);}
 const stars=1+(mistakes===0?1:0)+(hearts===2?1:0);
 return <main className="wave-page"><header><a className="brand" href="?view=map"><span>VALLE</span> ESMERALDA<small>UNA AVENTURA POR DESCUBRIR</small></a><div className="chapter"><span>CAPÍTULO 09</span><strong>{level.name}</strong></div><div className="inventory"><span>★ <b>{status==='won'?stars:0}</b><small>/ 3</small></span><span>◆ <b>{status==='won'?1:0}</b><small>/ 1</small></span><span className="energy">{Array.from({length:2},(_,i)=>i<hearts?'♥':'♡').join(' ')}</span></div><HubLinks/></header>
 <section className="wave-game"><svg viewBox="0 0 1200 720" role="img" aria-label="Islas flotantes atravesadas por una corriente de energía ondulada"><image href="./art/wave-islands.webp" width="1200" height="800" preserveAspectRatio="xMidYMid slice"/><rect className="wave-glass" x="70" y="205" width="1060" height="390" rx="30"/><line className="wave-axis" x1="110" y1="400" x2="1110" y2="400"/><path className="wave-guide" d={wavePath(choice)}/><g className="wave-rings">{checkpoints.map((point,i)=><g key={i} transform={`translate(${point.x} ${point.y})`}><circle r="23"/><circle r="10"/><text y="-31">{i+1}</text></g>)}</g>{orb&&<g className="wave-orb" transform={`translate(${orb.x} ${orb.y})`}><circle r="18"/><circle r="7"/></g>}<image href="./art/hero-dodge.webp" x="20" y="500" width="105" height="115"/><image href="./art/cannon-transparent.webp" x="82" y="520" width="145" height="104"/><g className="wave-mission"><rect x="285" y="28" width="630" height="125" rx="20"/><text x="600" y="62">CORRIENTE {round+1}/3 {data.time?`· ${seconds} s`:''}</text><text x="600" y="101">{target.f==='sin'?'SENO':'COSENO'} · ALTURA {target.a===50?'BAJA':target.a===90?'MEDIA':'ALTA'} · RITMO {target.b}</text><text x="600" y="130">{level.id>=50?`y = ${target.a} · ${target.f==='sin'?'sen':'cos'}(${target.b}x + ${PHASES[target.p]})`:`DESPLAZAMIENTO ${PHASES[target.p]}`}</text></g></svg>
 <div className="wave-controls"><div className="wave-control"><label>ALTURA DE OLA</label><input type="range" min="0" max="2" value={AMPLITUDES.indexOf(choice.a)} onChange={e=>set('a',AMPLITUDES[Number(e.target.value)])}/><small>BAJA · MEDIA · ALTA</small></div>{showFrequency&&<div className="wave-control"><label>RITMO</label><input type="range" min="1" max="3" value={choice.b} onChange={e=>set('b',Number(e.target.value))}/><small>1 · 2 · 3 ondas</small></div>}{showPhase&&<div className="wave-control"><label>DESPLAZAMIENTO</label><input type="range" min="0" max="3" value={choice.p} onChange={e=>set('p',Number(e.target.value))}/><small>{PHASES[choice.p]}</small></div>}{showFamily&&<div className="wave-family"><button className={choice.f==='sin'?'active':''} onClick={()=>set('f','sin')}>SENO</button><button className={choice.f==='cos'?'active':''} onClick={()=>set('f','cos')}>COSENO</button></div>}<button className="wave-launch" disabled={status!=='aim'} onClick={launch}>✦ ACTIVAR CORRIENTE</button></div>
 {status==='correct'&&<div className="wave-feedback success">¡Los tres aros vibraron en armonía!</div>}{status==='flying'&&<div className="wave-feedback">La energía recorre la corriente…</div>}
 {status==='won'&&<div className="victory"><div className="win-star">{'★'.repeat(stars)}</div><small>{worldComplete?'MUNDO COMPLETADO':'ISLA CONQUISTADA'}</small><h1>¡Dominaste la corriente!</h1><p>Tu onda atravesó los tres cristales de cada recorrido.</p><div className="rewards">★ {stars} estrellas <span>◆ 1 cristal</span></div><button onClick={onNext}>{worldComplete?'MUNDO COMPLETADO · VOLVER AL MAPA →':'Siguiente isla →'}</button></div>}{status==='lost'&&<div className="victory defeat"><div className="win-star">♡</div><small>LA CORRIENTE SE DISIPÓ</small><h1>Observa los tres aros</h1><p>Ajusta altura, ritmo y desplazamiento hasta que toda la onda atraviese los cristales.</p><button onClick={()=>location.reload()}>Reintentar ↻</button></div>}
 </section><footer><div className="guide-icon">≈</div><p>Haz que la corriente luminosa atraviese los tres aros antes de activarla.</p><span>Intento {round+1}/3</span></footer></main>;
}

